# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('size', models.CharField(max_length=4)),
                ('icon', models.CharField(max_length=50)),
                ('order', models.SmallIntegerField()),
                ('message', models.CharField(default='', max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'gift',
            },
        ),
        migrations.CreateModel(
            name='GiftOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('to_user_id', models.IntegerField()),
                ('gift_id', models.SmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('status', models.SmallIntegerField(default=0)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gift_order',
            },
        ),
    ]
