# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livemedialog',
            name='channel_type',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='livemedialog',
            name='type',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='livemedialog',
            name='user_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
