# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='pid',
            new_name='creator_id',
        ),
        migrations.AddField(
            model_name='inviteparty',
            name='channel_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='inviteparty',
            name='party_type',
            field=models.SmallIntegerField(default=0),
        ),
    ]
