# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='invite_user_id',
            field=models.IntegerField(default=0),
        ),
    ]
