# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0002_channel_invite_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('to_user_id', models.IntegerField()),
                ('channel_id', models.CharField(max_length=50)),
                ('status', models.SmallIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='channel',
            name='invite_user_id',
        ),
        migrations.AddField(
            model_name='channel',
            name='is_lock',
            field=models.BooleanField(default=False),
        ),
    ]
