# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-26 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live', '0003_auto_20170523_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='livelocklog',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
