# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletrecord',
            name='category',
            field=models.SmallIntegerField(default=0),
        ),
    ]
