# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_walletrecord_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletrecord',
            name='to_user_id',
        ),
        migrations.AddField(
            model_name='walletrecord',
            name='owner_id',
            field=models.IntegerField(default=0),
        ),
    ]
