# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ignore',
            old_name='user_id',
            new_name='ignore_id',
        ),
        migrations.RenameField(
            model_name='ignore',
            old_name='type',
            new_name='ignore_type',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='', max_length=40),
        ),
    ]
