# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170327_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('friend_id', models.IntegerField()),
                ('status', models.SmallIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('first_name', models.CharField(default='', max_length=20)),
                ('last_name', models.CharField(default='', max_length=20)),
                ('mobile', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'user_contact',
            },
        ),
        migrations.RemoveField(
            model_name='thirduser',
            name='user_id',
        ),
        migrations.AddField(
            model_name='thirduser',
            name='mobile',
            field=models.CharField(db_index=True, default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='tempthirduser',
            name='avatar',
            field=models.CharField(max_length=255),
        ),
    ]
