# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelAddFriendLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('friend_id', models.IntegerField()),
                ('channel_type', models.SmallIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='grade',
            field=models.CharField(default='', max_length=20),
        ),
    ]
