# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-18 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20170517_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ignore',
            name='owner_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
