# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_ignore'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteFirend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('invited_id', models.IntegerField()),
                ('status', models.SmallIntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='firend',
            name='status',
        ),
    ]
