# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20170502_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='is_hint',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='channeladdfriendlog',
            table='channel_add_friend_log',
        ),
    ]
