# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20170404_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='is_import_contact',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([]),
        ),
    ]
