# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userdynamic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdynamic',
            name='is_paing',
        ),
        migrations.AddField(
            model_name='userdynamic',
            name='paing',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdynamic',
            name='last_pa_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
