# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20170404_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='notify_switch',
            field=models.BooleanField(default=True),
        ),
    ]
