# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userdynamic'),
    ]

    operations = [
        
    ]
