# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20170607_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdynamic',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
