# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20170405_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempthirduser',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tempthirduser',
            name='wx_unionid',
            field=models.CharField(default='', max_length=50),
        ),
    ]
