# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-11 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20170608_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdynamic',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
