# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20170411_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='memo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
