# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-12 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20170612_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('to_user_id', models.IntegerField()),
                ('type', models.SmallIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
            ],
            options={
                'db_table': 'user_report',
            },
        ),
    ]
