# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 08:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_userreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialReportUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'special_report_user',
            },
        ),
    ]
