# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_specialreportuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('type', models.SmallIntegerField()),
                ('category', models.SmallIntegerField()),
                ('extras', models.CharField(default='', max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'logs',
            },
        ),
    ]
