# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_pokelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='offline_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='online_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
