# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20170418_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokelog',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
