# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20170419_0800'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friend',
            unique_together=set([('user_id', 'friend_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='invitefriend',
            unique_together=set([('invited_id', 'user_id')]),
        ),
    ]
