# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20170420_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='notify_switch',
            new_name='push',
        ),
        migrations.AddField(
            model_name='friend',
            name='invisible',
            field=models.BooleanField(default=False),
        ),
    ]
