# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=20)),
                ('group', models.SmallIntegerField()),
            ],
        ),
    ]
