# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ida', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duty',
            name='group',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='duty',
            name='mobile',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='duty',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
